{{- if .Values.env.config}}
apiVersion: v1
kind: ConfigMap
metadata:
 {{- if lower .Values.sename}}
 name: {{ lower .Values.name }}-{{ lower .Values.sename }}
 {{- else }}
 name: {{lower .Values.name}}
 {{- end }} 
data:
{{.Values.env.config | toYaml | indent 2}}
---
{{- end}}

{{- if .Values.env.secrets}}
apiVersion: v1
kind: Secret
metadata:
 {{- if lower .Values.sename}}
 name: {{ lower .Values.name }}-{{ lower .Values.sename }}
 {{- else }}
 name: {{lower .Values.name}}
 {{- end }} 
stringData:
{{.Values.env.secrets | toYaml | indent 2}}
---
{{- end}}

{{- if .Values.dockercfg}}
apiVersion: v1
kind: Secret
metadata:
  {{- if lower .Values.sename }}
  name: {{ lower .Values.name }}-{{ lower .Values.sename }}-dockercfg
  {{- else }}
  name: {{ lower .Values.name }}
  {{- end }}
  annotations:
    harness.io/skip-versioning: true
data:
  .dockercfg: {{.Values.dockercfg}}
type: kubernetes.io/dockercfg
---
{{- end}}

apiVersion: apps/v1
kind: Deployment
metadata:
 {{- if lower .Values.sename}}
 name: {{ lower .Values.name }}-{{ lower .Values.sename }}-deployment
 {{- else }}
 name: {{lower .Values.name}}-deployment
 {{- end }} 
spec:
  replicas: {{int .Values.replicas}}
  selector:
    matchLabels:
     {{- if lower .Values.sename}}
      app: {{ lower .Values.name }}-{{ lower .Values.sename }}
     {{- else }}
      app: {{ lower .Values.name }}
     {{- end }} 
  template:
    metadata:
      labels:
        {{- if lower .Values.sename}}
        app: {{ lower .Values.name }}-{{ lower .Values.sename }}
        {{- else }}
        app: {{ lower .Values.name }}
        {{- end }} 
    spec:
      {{- if .Values.dockercfg}}
      imagePullSecrets:
      {{- if lower .Values.sename }}
      - name: {{ lower .Values.name }}-{{ lower .Values.sename }}-dockercfg
      {{- else }}
      - name: {{ lower .Values.name }}-dockercfg
      {{- end}}
      {{- end}}
      containers:
      {{- if lower .Values.sename }}
      - name: {{ lower .Values.name }}-{{ lower .Values.sename }}
      {{- else }}
      - name: {{ lower .Values.name }}
      {{- end}}
        image: {{ .Values.image }}
        {{- if or .Values.env.config .Values.env.secrets}}
        imagePullPolicy: Always
        envFrom:
        {{- if .Values.env.config}}
        - configMapRef:
            {{- if lower .Values.sename }}
            name: {{ lower .Values.name }}-{{ lower .Values.sename }}
            {{- else}}
            name: {{ lower .Values.name }}
            {{- end}}
        {{- end}}
        {{- if .Values.env.secrets}}
        - secretRef:
            {{- if lower .Values.sename }}
            name: {{ lower .Values.name }}-{{ lower .Values.sename }}
            {{- else}}
            name: {{ lower .Values.name }}
            {{- end}}
        {{- end}}
        {{- end}}
